### ISSUE TITLE
Use multiple accounts?

### ISSUE THREAD

**Issue by Juancafr** [TheNetsky/Microsoft-Rewards-Script#124]
I don't know if it is possible to use multiple accounts and prevent them from being suspended. If yes, any advice to avoid it?

**Comment by serzak51** [comment]
Using multiple accounts aren't really an issue (It sometimes needs some inputs because microsoft is doing shenanigans). Even on the same IP, it seems that you can have multiple accounts and it won't be a problem
But you may face 2 problem: first, you can't run 2 scripts in parrallel with the same IP. I don't think it can be ban, but none of the script will work. If you want to make in parrallel, either you purchase a paid proxy (don't bother with free ones, from my experience they never works), or you can try to tinker with tor to make it act as a proxy
You will also have problems to create accounts. The official limit is 3 accounts/day/ip. But after creating 6-9 accounts, they will still looks fine, but they won't work the following day. The trick is to uninstall and reinstall the browser (ungoogled chromium is great for that, as there isn't any prompt in the installation). The advantage is that you also don't get affected by the limits anymore (Tinker with it if you want, cuz normally it should not bypass it).

**Comment by Juancafr** [comment]
Okay I understand. Another different thing I want to ask and not have to open another thread. Is there any way to send the log to Telegram of when it has finished? something automatic so you know it was done well without having to look at it every day

**Comment by serzak51** [comment]
With the webhook settings maybe? I am not really sure, since i never used telegram
But you would probably be better off by settings a remote desktop like rustdesk and accessing the script with it, because as i said it as a tendancy to block itself, and while it probably won't break everything, you will still get less points in total for the same processing power/bandwidth

**Comment by TheNetsky** [comment]
No telegram support, only Discord.
