### ISSUE TITLE
Sometimes searches fail me. Should you modify the settings?

### ISSUE THREAD

**Issue by Juancafr** [TheNetsky/Microsoft-Rewards-Script#126]
I have been using the script for a short time and the first few days it worked correctly, but since yesterday the last account fails in the searches and I have to run the script several times. Could it be something in the config? I have not touched it, it is as it comes by default

**Comment by serzak51** [comment]
As it is it's going to be hard to help. What error message to get? are the credential correct? Did the account got banned? Is there a fullscreen cookie popup on this account? Whitout the error message it's pretty difficult to know where the issue lie

**Comment by Juancafr** [comment]
> As it is it's going to be hard to help. What error message to get? are the credential correct? Did the account got banned? Is there a fullscreen cookie popup on this account? Whitout the error message it's pretty difficult to know where the issue lie

It fails me in mobile searches, I don't remember the error now, but it was the type of retry 5 times. Likewise, what I did was create a task so that the script would run three times a day every 4 hours and for now it works

**Comment by TheNetsky** [comment]
And you're not in one of those countries where its x searches per 15min?

**Comment by Juancafr** [comment]
> And you're not in one of those countries where its x searches per 15min?

I am from Spain

**Comment by TheNetsky** [comment]
Yeah, I don't know which countries have and have not. Check manually youself if that's the case.

**Comment by serzak51** [comment]
I think i see the error you are talking about. Yeah i also sometimes get that. If it's just this error, leave it alone, and it will still proceed through unless something is making it stuck. It can also be the cookie pop-up causing trouble, sometimes along side the cmd flooding it will also pop up this error. Though if you don't get the message anymore, it's probably resolved (at least for this account), since the first one is temporary and i have no idea why sometimes it put this error, and the second one can only go away when the cookie is accepted, and normally cannot come back
