### ISSUE TITLE
1.5 sometimes can't get dashboard data

### ISSUE THREAD

**Issue by serzak51** [TheNetsky/Microsoft-Rewards-Script#184]
When running the script, most of the time it's fine, and then suddenly, when trying to get the dashboard data, i get this error:

```
[11/11/2024 15:13:23] [PID: 17724] [ERROR] DESKTOP [GET-DASHBOARD-DATA] Dashboard data not found within script
[11/11/2024 15:13:23] [PID: 17724] [ERROR] DESKTOP [MAIN-ERROR] Error running bots: undefined
```

This error only happens on desktop browser, mobile aren't affected. I am not sure where it could come from. The script just stay on the reward page, and do nothing else.
I could see 2 solution to this problem: either making it tries multiple time (it's not impossible that it's just a one time blockage from microsoft), or just ignore the error and make the script continue (if i understand correctly, the function is to get the current points count, so if he can't parse the point count, we could just say that it's an unknown number, and assume that the points decreased/increased like it should. The error is rare enough that it shouldn't make the script run empty for hours). Or last solution, there is an actual fix that i didn't saw

**Comment by TheNetsky** [comment]
There's no difference in the gathering of the info between 1.5 and prior, this seems to be an issue on your end however since I've not had this happen. Gathering dashboard data is in general a important function, skipping it will only seemingly cause more issues, this function is also ran quite often during the running of the script.
